export const PLANTIO_ACTIONS_TYPES = {
	SET_PLANTIO: "plantio/SET_PLANTIO",
	SET_APP: "plantio/SET_APP",
	SET_APP_FARMBOX: "plantio/SET_APP_FARMBOX",
	SET_SAFRA_CICLO: "plantio/SET_SAFRA_CICLO",
	SET_PLANTIO_MAP_ALL: "plantio/SET_PLANTIO_MAP_ALL",
	SET_PLUVI: "plantio/SET_PLUVI"
};
