export const PROJETOS_FAZENDAS = [
	{ id: 35, local: "Projeto 5 Estrelas" },
	{ id: 31, local: "Projeto Benção de Deus" },
	{ id: 42, local: "Projeto Biguá" },
	{ id: 43, local: "Projeto Cacíque" },
	{ id: 32, local: "Projeto Campo Guapo" },
	{ id: 5, local: "Projeto Capivara" },
	{ id: 7, local: "Projeto Cervo" },
	{ id: 46, local: "Projeto Diamante" },
	{ id: 12, local: "Projeto Eldorado" },
	{ id: 36, local: "Projeto Fazendinha" },
	{ id: 4, local: "Projeto Jacaré" },
	{ id: 44, local: "Projeto João de Barro" },
	{ id: 8, local: "Projeto Lago Verde" },
	{ id: 40, local: "Projeto Novo Acordo" },
	{ id: 1, local: "Projeto Ouro Verde" },
	{ id: 16, local: "Projeto Pau Brasil" },
	{ id: 10, local: "Projeto Praia Alta" },
	{ id: 2, local: "Projeto Safira" },
	{ id: 11, local: "Projeto Santa Maria" },
	{ id: 19, local: "Projeto São Pedro" },
	{ id: 3, local: "Projeto Tucano" },
	{ id: 6, local: "Projeto Tuiuiu" },
	{ id: 45, local: "UBS" },
	{ id: 47, local: "Outros" },
	{ id: "D3", local: "Fazenda Biguá" },
	{ id: "D4", local: "Fazendão" },
	{ id: "D5", local: "Agronorte" },
	{ id: "D6", local: "Cajueiro" },
	{ id: "D7", local: "JK" },
	{ id: "D8", local: "FTS" }
];
